//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.24 at 10:54:10 AM MSK 
//


package ru.alta.svd.protocol.test.dto;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Pay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="payRub" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OperationResult">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="File" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="statId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "pay",
        "days",
        "payRub",
        "operationResult",
        "file"
})
@XmlRootElement(name = "XMLFile")
public class XMLFile {

    @XmlElement(name = "Pay")
    protected String pay;
    protected String days;
    protected String payRub;
    @XmlElement(name = "OperationResult", required = true)
    protected XMLFile.OperationResult operationResult;
    @XmlElement(name = "File")
    protected List<XMLFile.File> file;

    /**
     * Gets the value of the pay property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPay() {
        return pay;
    }

    /**
     * Sets the value of the pay property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPay(String value) {
        this.pay = value;
    }

    /**
     * Gets the value of the days property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDays() {
        return days;
    }

    /**
     * Sets the value of the days property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDays(String value) {
        this.days = value;
    }

    /**
     * Gets the value of the payRub property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPayRub() {
        return payRub;
    }

    /**
     * Sets the value of the payRub property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPayRub(String value) {
        this.payRub = value;
    }

    /**
     * Gets the value of the operationResult property.
     *
     * @return possible object is
     * {@link XMLFile.OperationResult }
     */
    public XMLFile.OperationResult getOperationResult() {
        return operationResult;
    }

    /**
     * Sets the value of the operationResult property.
     *
     * @param value allowed object is
     *              {@link XMLFile.OperationResult }
     */
    public void setOperationResult(XMLFile.OperationResult value) {
        this.operationResult = value;
    }

    /**
     * Gets the value of the file property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the file property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFile().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLFile.File }
     */
    public List<XMLFile.File> getFile() {
        if (file == null) {
            file = new ArrayList<XMLFile.File>();
        }
        return this.file;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="statId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "id",
            "login",
            "statId",
            "content"
    })
    public static class File {

        @XmlElement(required = true)
        protected String id;
        protected String login;
        @XmlElement(required = true)
        protected String statId;
        @XmlElement(required = true)
        protected byte[] content;

        /**
         * Gets the value of the id property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the login property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getLogin() {
            return login;
        }

        /**
         * Sets the value of the login property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setLogin(String value) {
            this.login = value;
        }

        /**
         * Gets the value of the statId property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getStatId() {
            return statId;
        }

        /**
         * Sets the value of the statId property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setStatId(String value) {
            this.statId = value;
        }

        /**
         * Gets the value of the content property.
         *
         * @return possible object is
         * byte[]
         */
        public byte[] getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         *
         * @param value allowed object is
         *              byte[]
         */
        public void setContent(byte[] value) {
            this.content = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "state",
            "message",
            "messageEx",
            "ignores"
    })
    public static class OperationResult {

        @XmlElement(required = true)
        protected Integer state;
        protected String message;
        @XmlElement(name = "messageEx ", required = false)
        private String messageEx;

        @XmlElement(name = "ignores ", required = false)
        private String ignores;


        public String getMessageEx() {
            return messageEx;
        }
        /**
         * Gets the value of the state property.
         *
         * @return possible object is
         * {@link String }
         */
        public Integer getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setState(Integer value) {
            this.state = value;
        }

        /**
         * Gets the value of the message property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMessage(String value) {
            this.message = value;
        }

        public void setMessageEx(String messageEx) {
            this.messageEx = messageEx;
        }

        public String getIgnores() {
            return ignores;
        }

        public void setIgnores(String ignores) {
            this.ignores = ignores;
        }
    }

}
